### ISSUE TITLE
Bookmarklet silently failing + crossorigin.me seems gone

### ISSUE THREAD

**Issue by emilbjorklund** [ausi/respimagelint#35]
Hi! First up: this is a thoroughly useful bookmarklet!

Tried it out a little while ago, and managed to get some results. However, it seems I can't get it working on most sites I try it on at the moment. It get's stuck on the `Resizing to 300x169` step.

I haven't done any deep digging (any error from the bookmarklet itself seems to be silently swallowed), but the first thing I noticed was that in Safari, the tests ran, but there they throw up a load of 404:s in the console: the `crossorigin.me` site seems to be gone.

**Comment by ausi** [comment]
Should be fixed in the newest version, see f000039aa5b7220848c231b20f8a0f17d74e84dc

@emilbjorklund can you please verify if the fix works for you?

**Comment by emilbjorklund** [comment]
Cheers – got it working in Safari at least, but loads of errors due to Too Many Requests to `cors-anywhere` (eek, lots of images on the site I tested with).

Still not working in Firefox or Chrome though – give it a spin on e.g. https://theguardian.com – stops at the same step. If I'd had to guess, I'd say it has to do with CORS, but haven't done enough digging to be sure – sorry.

**Comment by ausi** [comment]
> Still not working in Firefox or Chrome though – give it a spin on e.g. [theguardian.com](https://theguardian.com)

Chrome worked in my test, but takes very long because of all the ads and hundreds of images.

> but loads of errors due to Too Many Requests to `cors-anywhere` (eek, lots of images on the site I tested with).

Running the bookmarklet on large pages with hundreds of images is currently problematic. The CORS proxy is only needed if you host your images on a different domain.

To overcome these issues I have to rewrite the bookmarklet as a browser dev tools extension I think. See https://github.com/ausi/respimagelint/issues/10#issuecomment-616762862

**Comment by emilbjorklund** [comment]
Right - got it! Completely understand that it's tricky to make it work for larger sites.

**Comment by Jashi** [comment]
Maybe some more data helps :)

I tried https://www.seeburger.com today and I can see the resizing to 300x169 overlay forever (several minutes). The page doesn't have that many images but they are lazyloaded and some are in a slider (also lazyloaded). No console error - just stuck forever in Chrome and FF.

On the other hand the site https://www.bruker.com has way more images and it doesn't get stuck on resizing (JS still dies later but that isn't from this bug I'm assuming). The lazyloading is only done for the sliders, nothing else.

**Comment by tanc** [comment]
`cors-anywhere` has been mostly taken down: https://github.com/Rob--W/cors-anywhere/issues/301

**Comment by ausi** [comment]
Does anyone know an alternative free CORS proxy that we can use?

**Comment by cascading-jox** [comment]
I also get the silent failure on latest firefox but chrome is working for me (under Linux)
